name: Change metadata of PDF

on: [push]

jobs:
  sample_action:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: checkout # Checkout current repository
      uses: actions/checkout@master

    - name: Change metadata of PDF file # Changes metadata of sample.pdf file
      uses: ./ # Uses an action in the root directory
      with:
        file: ./sample.pdf
        title: Sample Title
        author: John Doe

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
