name: Change metadata of PDF

on: [push]

jobs:
  sample_action:
    runs-on: ubuntu-latest
    name: Changing metadata
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: Change metadata of PDF file
      uses: ./ # Uses an action in the root directory
      with:
        file: ./sample.pdf
        title: Sample Title
        author: John Doe
