on: [push]

jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: Changing metadata
    steps:
    - name: Change metadata of PDF file
      uses: ./ # Uses an action in the root directory
      with:
        file: ./sample.pdf
        title: Sample Title
        author: John Doe
